In [1]:
import pandas as pd

In [2]:
fire_df = pd.read_csv('../Raw_Data/California_Fire_Incidents.csv')
fire_df.head()

,AcresBurned,Active,AdminUnit,AirTankers,ArchiveYear,CalFireIncident,CanonicalUrl,ConditionStatement,ControlStatement,Counties,...,SearchKeywords,Started,Status,StructuresDamaged,StructuresDestroyed,StructuresEvacuated,StructuresThreatened,UniqueId,Updated,WaterTenders
0,257314.0,False,Stanislaus National Forest/Yosemite National Park,NaN,2013,True,/incidents/2013/8/17/rim-fire/,NaN,NaN,Tuolumne,...,"Rim Fire, Stanislaus National Forest, Yosemite...",2013-08-17T15:25:00Z,Finalized,NaN,NaN,NaN,NaN,5fb18d4d-213f-4d83-a179-daaf11939e78,2013-09-06T18:30:00Z,NaN
1,30274.0,False,USFS Angeles National Forest/Los Angeles Count...,NaN,2013,True,/incidents/2013/5/30/powerhouse-fire/,NaN,NaN,Los Angeles,...,"Powerhouse Fire, May 2013, June 2013, Angeles ...",2013-05-30T15:28:00Z,Finalized,NaN,NaN,NaN,NaN,bf37805e-1cc2-4208-9972-753e47874c87,2013-06-08T18:30:00Z,NaN
2,27531.0,False,CAL FIRE Riverside Unit / San Bernardino Natio...,NaN,2013,True,/incidents/2013/7/15/mountain-fire/,NaN,NaN,Riverside,...,"Mountain Fire, July 2013, Highway 243, Highway...",2013-07-15T13:43:00Z,Finalized,NaN,NaN,NaN,NaN,a3149fec-4d48-427c-8b2c-59e8b79d59db,2013-07-30T18:00:00Z,NaN
3,27440.0,False,Tahoe National Forest,NaN,2013,False,/incidents/2013/8/10/american-fire/,NaN,NaN,Placer,...,"American Fire, August 2013, Deadwood Ridge, Fo...",2013-08-10T16:30:00Z,Finalized,NaN,NaN,NaN,NaN,8213f5c7-34fa-403b-a4bc-da2ace6e6625,2013-08-30T08:00:00Z,NaN
4,24251.0,False,Ventura County Fire/CAL FIRE,NaN,2013,True,/incidents/2013/5/2/springs-fire/,Acreage has been reduced based upon more accur...,NaN,Ventura,...,"Springs Fire, May 2013, Highway 101, Camarillo...",2013-05-02T07:01:00Z,Finalized,6.0,10.0,NaN,NaN,46731fb8-3350-4920-bdf7-910ac0eb715c,2013-05-11T06:30:00Z,11.0

In [9]:
fire_df = fire_df[['AcresBurned', 'ArchiveYear', 'CalFireIncident', 'Counties']]
fire_df

      AcresBurned  ArchiveYear  CalFireIncident     Counties
0        257314.0         2013             True     Tuolumne
1         30274.0         2013             True  Los Angeles
2         27531.0         2013             True    Riverside
3         27440.0         2013            False       Placer
4         24251.0         2013             True      Ventura
...           ...          ...              ...          ...
1631          9.0         2019             True    Riverside
1632          2.0         2019             True       Nevada
1633          NaN         2019            False         Yolo
1634          NaN         2019            False    San Diego
1635          NaN         2019            False    Riverside

[1636 rows x 4 columns]

In [7]:
fire_df.dtypes

AcresBurned        float64
ArchiveYear          int64
CalFireIncident       bool
Counties            object
dtype: object

In [16]:
fire_df = fire_df.dropna()
fire_df

      AcresBurned  ArchiveYear  CalFireIncident     Counties
0        257314.0         2013             True     Tuolumne
1         30274.0         2013             True  Los Angeles
2         27531.0         2013             True    Riverside
3         27440.0         2013            False       Placer
4         24251.0         2013             True      Ventura
...           ...          ...              ...          ...
1628         10.0         2019             True        Butte
1629         10.0         2019             True     Siskiyou
1630         10.0         2019             True        Butte
1631          9.0         2019             True    Riverside
1632          2.0         2019             True       Nevada

[1633 rows x 4 columns]

In [17]:
fire_df.to_csv('../Clean_Data/CLEAN_wildfire_data.csv', index=False)